# Generated by Django 4.2.1 on 2023-05-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_transaction_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(default='None', max_length=24),
        ),
    ]
